SELECT * FROM INFORMATION_SCHEMA.TABLES


SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers' or TABLE_NAME = 'dim_products' or TABLE_NAME = 'fact_sales'

SELECT * FROM dbo.dim_products

-- DIMESION EXPLORATION
		-- EXPLORE ALL COUNTRIES OUR CUSTOMERS COME FROM 
			SELECT DISTINCT country FROM DataWarehouseAnalytics.dbo.dim_customers
		-- EXPLORE ALL CATEGORIES 
			SELECT DISTINCT category, subcategory, product_name FROM DataWarehouseAnalytics.dbo.dim_products
			ORDER BY 1,2,3
-- DATE EXPLORATION 
		-- IDENTIFY THE EARLIEST AND LATEST DATES(BOUNDRIES)  _____> TO UNDERSTAND THE TIMESPAN 
			--IDENTIFY THE FIRST AND LAST ORDER 
					SELECT 
					MIN(order_date) FirstOrderDate,
					MAX(order_date) LastOrderDate,
			-- HOW MANY YEARS OF SALES ARE AVAILABLE 
					DATEDIFF(MONTH, MIN(order_date),MAX(order_date)) DurationOfTheYear
					FROM DataWarehouseAnalytics.dbo.fact_sales
		-- FIND THE YOUNGEST AND OLDEST CUST 
			SELECT MIN(birthdate) Youngest, MAX(birthdate) Oldest, DATEDIFF(YEAR,MIN(birthdate), GETDATE()) LargerAge, 
			DATEDIFF(YEAR, MAX(birthdate), GETDATE()) SmallerAge 
			FROM DataWarehouseAnalytics.dbo.dim_customers


--------------------------------------------------------
-- MEASURE EXPLORATION 
	--1 FIND THE TOTAL SALES
		SELECT SUM(sales_amount) AS TotalSales FROM dbo.fact_sales
--2 FIND HOW MANY ITEMS ARE SOLD 
		SELECT SUM(quantity) AS Quantity_Of_Items_Sold FROM dbo.fact_sales
--3 FIND THE AVERAGE SELLING PRICE 
		SELECT AVG(price) AS Avg_Of_Price FROM dbo.fact_sales
--4 FIND THE TOTAL NUMBER OF ORDERS	
		SELECT COUNT(order_number) AS Total_Orders FROM dbo.fact_sales
		SELECT COUNT(DISTINCT order_number) AS Total_Orders FROM dbo.fact_sales

--5 FIND THE TOTAL NUMBER OF PRODUCTS
		SELECT COUNT(product_key) AS Total_products FROM dbo.dim_products
		SELECT COUNT(DISTINCT product_key) AS Total_products FROM dbo.dim_products
		SELECT COUNT(product_name) AS Total_products FROM dbo.dim_products

--6 FIND THE TOTAL NUMBER OF CUSTOMERS 
		SELECT COUNT(customer_key) AS Total_customers FROM dbo.dim_customers

--7 FIND THE TOTAL NUMBER OF CUSTOMERS THAT HAS PLACED AN ORDER
		-- يعني هنانة ممكن الزبون الواحد يطلب اكثر من شغلة وحدة، واني اريد عدد الزبائن وليس عدد الطلبات
		SELECT COUNT(DISTINCT customer_key) TotalCustomerOrdered FROM dbo.fact_sales

-- The big pictures
			SELECT 'Total_Sales' AS MeasureName, SUM(sales_amount) AS MeasureValue FROM dbo.fact_sales
			UNION ALL
			SELECT 'Total_Items_Sold' AS MeasureName, SUM(quantity) AS Quantity_Of_Items_Sold FROM dbo.fact_sales
			UNION ALL
			SELECT 'Avg_Price' AS MeasureName, AVG(price) AS Avg_Of_Price FROM dbo.fact_sales
			UNION ALL
			SELECT 'Total_Orders' AS MeasureName, COUNT(DISTINCT order_number) AS Total_Orders FROM dbo.fact_sales
			UNION ALL
			SELECT 'Total_Products' AS MeasureName, COUNT(product_name) AS Total_products FROM dbo.dim_products
			UNION ALL
			SELECT 'Total_Customers' AS MeasureName, COUNT(customer_key) AS Total_customers FROM dbo.dim_customers
			UNION ALL
			SELECT 'Total_Customers_Ordered' AS MeasureName, COUNT(DISTINCT customer_key) TotalCustomerOrdered FROM dbo.fact_sales

--------------------------------------------------------------------

-- Magnitude analysis     LOW CARDINALITY DIMENSION AND HIGH CARDINALITY DIMENSION
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
--1 FIND THE TOTAL CUSTOMERS BY COUNTRIES 11111111111111111111111111111111111111111111
	SELECT country, COUNT(customer_key) TotalCustomers FROM dbo.dim_customers
	GROUP BY country
	ORDER BY TotalCustomers DESC
--2 FIND TOTAL CUSTOMERS BY GENDER
	SELECT gender, COUNT(customer_key) TotalCustomers FROM dbo.dim_customers
	GROUP BY gender
	ORDER BY TotalCustomers DESC
--3  FIND TOTAL PRODUCTS BY CATEGORY
	SELECT category, COUNT(product_name) TotalProducts FROM dbo.dim_products
	GROUP BY category
	ORDER BY TotalPRoducts DESC
--4  WHAT IS THE AVERAGE COSTS IN EACH CATEGORY 
	SELECT category, AVG(cost) AvgCost FROM dbo.dim_products
	GROUP BY category
	ORDER BY AvgCost DESC

--5 WHAT IS THE TOTAL REVENUE GENERATED FOR EACH CATEGORY
	SELECT p.category, SUM(s.sales_amount) AS TotalRevenue FROM dbo.dim_products p
	RIGHT JOIN dbo.fact_sales s ON p.product_key = s.product_key
	GROUP BY p.category
	ORDER BY TotalRevenue DESC
--6 FIND TOTAL REVENUE IS GENERATED BY EACH CUSTOMER
	SELECT c.customer_key, CONCAT(c.first_name,' ', c.last_name) AS CustomerName, SUM(s.sales_amount) AS TotalRevenue FROM dbo.dim_customers c
	RIGHT JOIN dbo.fact_sales s ON c.customer_key = s.customer_key
	GROUP BY c.customer_key, CONCAT(c.first_name,' ', c.last_name)
	ORDER BY TotalRevenue DESC
--8 WHAT IS THE DISTRIBUTION OF SOLD ITEMS ACROSS COUNTRIES
	SELECT c.country, SUM(s.quantity) TotalSoldItems FROM dbo.fact_sales s
	LEFT JOIN dbo.dim_customers c ON s.customer_key = c.customer_key
	GROUP BY c.country
	ORDER BY TotalSoldItems DESC
-------------------------------------------
-- Ranking Analysis
--1 WHICH 5 PRODUCTS GENERATE THE HIGHEST REVENUE 
		SELECT * FROM (
		SELECT p.product_name, SUM(s.sales_amount) TotalRevenue, ROW_NUMBER() OVER(ORDER BY SUM(s.sales_amount) DESC) AS RANKING FROM dbo.fact_sales s
		LEFT JOIN dbo.dim_products p ON s.product_key = p.product_key
		GROUP BY p.product_name)t
		WHERE RANKING <= 5

--2 WHAT ARE THE 5 WORST-PERFORMING PRODUCTS IN TERMS OF SALES
		SELECT * FROM (
		SELECT p.product_name, SUM(s.sales_amount) TotalRevenue, ROW_NUMBER() OVER(ORDER BY SUM(s.sales_amount) ASC) AS RANKING FROM dbo.fact_sales s
		LEFT JOIN dbo.dim_products p ON s.product_key = p.product_key
		GROUP BY p.product_name)t
		WHERE RANKING <= 5